[package]
name = "cli-client"
version = "0.1.0"
authors = ["Dennis Campagna <denniscampagna@gmail.com>"]
edition = "2018"

[features]
yaml = []

[dependencies]
clap = {version = "~2.27.0", features = ["yaml"]}
tikv-client = { git = "https://github.com/tikv/client-rust.git" }
rustyline = "5.0.0"